### ISSUE TITLE
my localhost is either not working, or correct address is unclear.

### ISSUE THREAD

**Issue by AnthonyBRoberts** [callmephilip/django-heroku-bootstrap#3]
Philip,

I would like to start with a huge Thank You for making your django-heroku-bootstrap open.  I've tried 5 or so different Heroku set-up tutorials, including the one on Heroku.com, and yours is the first that successfully deployed.  So you win mad props on that fact.

This seems like total newb question here, but what address is the localhost running on?  I installed Redis as directed (I think) but when I go to my usual localhost, it's "web page not available." I'm using localhost:8888 on my host machine (windows7), which is forwarded from port 8000 on my virtualbox, which is a vagrant installation.  

I thought maybe I was supposed to use localhost:6379 or something else, I don't know. This is the only thing in your documentation that seemed unclear to me.  

Actually, could this be because I'm not forwarding port 6379 from my virtualbox?  

Edit: I added port forwarding to the vagrant installation, and now localhost:6379 returns this:

-ERR wrong number of arguments for 'get' command
-ERR unknown command 'Host:'
-ERR unknown command 'Connection:'
-ERR unknown command 'Accept:'
-ERR unknown command 'User-Agent:'
-ERR unknown command 'Accept-Encoding:'
-ERR unknown command 'Accept-Language:'
-ERR unknown command 'Accept-Charset:'
-ERR unknown command 'Cookie:'
-ERR unknown command 'DNT:'

Thanks again, have a groovy day.

Anthony

**Comment by callmephilip** [comment]
@AnthonyBRoberts : not sure if I understand your question correctly. Local web server will be available on the port defined by $PORT env variable (see Procfile.dev for details). I believe the default for this one is 3000 so your server should be available on localhost:3000. 

Let me know if this works.

**Comment by AnthonyBRoberts** [comment]
This issue is resolved.  fab run shows after starting gunicorn that it's listening at http://0.0.0.0:5000  This isn't an issue with your work -- it was with me not forwarding the correct port with Vagrant -- sorry I presented it as an issue.  

Thank you for the response, and for sharing.

**Comment by callmephilip** [comment]
I am glad it works
