### ISSUE TITLE
Error raised re: ROOT_URLCONF locally

### ISSUE THREAD

**Issue by vfulco** [callmephilip/django-heroku-bootstrap#4]
After performing 'fab run' and starting the dev server, get 500 error when trying all/any URLS.  Error back is: AttributeError: 'Settings' object has no attribute 'ROOT_URLCONF'
[18/Jun/2013 10:23:23] "GET /examples HTTP/1.1" 500 59

Here is my ROOT_URLCONF = 'apps.urls' unchanged from the original code.  Tried changing it to just my project url, i.e. 'foo.urls', no change.  Also thought it might me related to imp module lookup so changed common.py to settings.py and naturally modded imports dev.py, static.py, prod.py but no luck there either.  Fairly new to Django so don't have solution yet.  TIA.

**Comment by callmephilip** [comment]
Might be a PATH issue. Could you try putting the folder where the app is in your PYTHONPATH env variable?

**Comment by vfulco** [comment]
Sure thing, i am bogged down rest of day but will try 1st thing tomorrow as
schedule is free in morning.  Thanks for timely response.

On Tue, Jun 18, 2013 at 11:00 AM, Philip Nuzhnyi
notifications@github.comwrote:

> Might be a PATH issue. Could you try putting the folder where the app is
> in your PYTHONPATH env variable?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/callmephilip/django-heroku-bootstrap/issues/4#issuecomment-19621301
> .

## 

Vince Fulco, CFA, CAIA
612.424.5477 (universal)
vfulco1@gmail.com
twitter: vfulco
app.net: vfulco

## 

"The combination of some data and an aching desire for an answer does not
ensure that a reasonable answer can be extracted from a

## given body of data. (John Tukey http://en.wikiquote.org/wiki/John_Tukey)"

Copy is the easiest way to store, protect and share amazing things. It
keeps your computers in sync and your files available from anywhere, even
on your mobile devices. With Copy, you can also easily share files with
anyone publicly or privately. Copy for companies extends the cloud storage
and sharing benefits into corporate environments with user and group
management and added control of proprietary company data. Free 5GB today!

https://copy.com?r=z2GhHq

**Comment by callmephilip** [comment]
@vfulco : did that work out?

**Comment by vfulco** [comment]
Apologies, jammed on a few other projects.  Will need to try it over the
weekend and come back to you.  Thanks for your inquiry and patience.  V.

On Thu, Jun 20, 2013 at 4:19 AM, Philip Nuzhnyi notifications@github.comwrote:

> @vfulco https://github.com/vfulco : did that work out?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/callmephilip/django-heroku-bootstrap/issues/4#issuecomment-19739366
> .

## 

Vince Fulco, CFA, CAIA
612.424.5477 (universal)
vfulco1@gmail.com
twitter: vfulco
app.net: vfulco

## 

"The combination of some data and an aching desire for an answer does not
ensure that a reasonable answer can be extracted from a

## given body of data. (John Tukey http://en.wikiquote.org/wiki/John_Tukey)"

Copy is the easiest way to store, protect and share amazing things. It
keeps your computers in sync and your files available from anywhere, even
on your mobile devices. With Copy, you can also easily share files with
anyone publicly or privately. Copy for companies extends the cloud storage
and sharing benefits into corporate environments with user and group
management and added control of proprietary company data. Free 5GB today!

https://copy.com?r=z2GhHq

**Comment by vfulco** [comment]
Turned out to be a path issue.  Thanks!

**Comment by callmephilip** [comment]
Great. Let me know if you have any other questions/problems
